### ISSUE TITLE
Epic: Adaptive Gameflow Mechanics

### ISSUE THREAD

**Issue by caoxantb** [caoxantb/g21-adhd-kinesthetic-game#13]
### Description

This epic focuses on designing game mechanics that create an engaging and adaptive experience for children, particularly those with ADHD. It involves the development of a dynamic game narrative with focus on movement and freezing mechanism, a reward and punishment system to motivate players, and scalable game levels that adjust to player abilities. The aim is to balance fun, focus, and challenge while accommodating the unique attention needs of children with ADHD.

### Features List
- [ ] Movements and Freeze-Frame Game Mechanism and Narrative
- [ ] Rewards and Punishments System
- [ ] Game Level Progression Mechanism
